import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,ChevronLeft,ChevronRight,Layers3,Pause,Play} from 'lucide-react';
import Chart from './Chart';
type Row=Record<string,any>;
const percent=(v:unknown)=>typeof v==='number'?`${(v*100).toFixed(1)}%`:'—';
const numeric=(v:unknown)=>typeof v==='number'?v.toFixed(2):'—';
const labels:Record<string,string>={threshold_ma:'Moving-average window',entry_threshold:'Entry deviation',exit_threshold:'Exit deviation',momentum_window:'Momentum lookback',vol_window:'Volatility window',low_vol_window:'Volatility lookback',top_n:'Positions',long_ma:'Long moving average',short_ma:'Short moving average',breakout_window:'Breakout lookback',amount_multiple:'Amount multiple',reversal_window:'Reversal lookback',exposure:'Target exposure'};
export default function Rolling({run,onMonth}:{run:{windows?:Row[];equity?:Row[];config:Row;selection_trials?:Row[]};onMonth:(m:string)=>void}) {
  const [index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1500);
  const windows=useMemo<Row[]>(()=>run.windows?.length?run.windows:Array.from({length:12},(_,i)=>{const month=new Date(Date.UTC(2025,6+i,1));const fmt=(offset:number)=>new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()+offset,1)).toISOString().slice(0,7);return {month:fmt(0),train_start:fmt(-15)+'-01',train_end:fmt(-4)+'-01',validation_start:fmt(-3)+'-01',validation_end:fmt(-1)+'-01'};}),[run.windows]);
  useEffect(()=>{setIndex(0);setPlaying(false);},[run.windows]);
  useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setIndex(value=>{if(value>=windows.length-1){setPlaying(false);return value;}return value+1;}),1500);return()=>clearInterval(timer);},[playing,windows.length,speed]);
  const w=windows[index]||windows[0], computed=w.selection_status!==undefined;
  const curve=(run.equity||[]).filter(e=>e.date>=w.signal_date&&e.date<=w.replay_end);
  return <><section className="panel rolling-panel"><div className="section-heading"><div><h2>One month forward. History behind it.</h2><p>Calibration, validation and a continuous portfolio replay.</p></div><span className="tag purple">{computed?'RECORDED ROLLING EXPERIMENT':'PROTOCOL PREVIEW'}</span></div><label className="replay-speed">Replay speed<select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={3000}>Slow</option><option value={1500}>Normal</option><option value={750}>Fast</option></select></label><div className="rolling-month"><span>REPLAY MONTH</span><h2>{new Date(w.month+'-02').toLocaleDateString('en',{month:'long',year:'numeric'})}</h2><div><button className="icon-button" aria-label="Previous rolling month" disabled={index===0} onClick={()=>{setPlaying(false);setIndex(index-1);}}><ChevronLeft size={20}/></button><button className="icon-button" aria-label={playing?'Pause rolling replay':'Play rolling replay'} onClick={()=>{if(index===windows.length-1)setIndex(0);setPlaying(!playing);}}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><button className="icon-button" aria-label="Next rolling month" disabled={index===windows.length-1} onClick={()=>{setPlaying(false);setIndex(index+1);}}><ChevronRight size={20}/></button></div></div><div className="timeline"><div className="train"><span>CALIBRATE</span><strong>{w.train_start.slice(0,7)} — {w.train_end.slice(0,7)}</strong><small>Rank candidate parameters</small></div><div className="validate"><span>VALIDATE</span><strong>{w.validation_start.slice(0,7)} — {w.validation_end.slice(0,7)}</strong><small>Select using past results</small></div><div className="replay"><span>REPLAY</span><strong>{w.month}</strong><small>Carry the ledger forward</small></div></div><input className="month-slider" type="range" min={0} max={windows.length-1} value={index} aria-label="Rolling replay month" onChange={e=>{setPlaying(false);setIndex(Number(e.target.value));}}/><div className="month-buttons">{windows.map((item,i)=><button key={item.month} className={i===index?'selected':''} onClick={()=>{setPlaying(false);setIndex(i);}}>{new Date(item.month+'-02').toLocaleString('en',{month:'short'})}<small>{item.month.slice(0,4)}</small></button>)}</div></section>
  <div className="rolling-bottom"><section className="panel">{computed?<><div className="section-heading"><div><h2>What happened next</h2><p>The actual month on a continuous equity ledger.</p></div><button className="link-button" onClick={()=>onMonth(w.month)}>Inspect trades<ArrowRight size={14}/></button></div><div className="inline-stats"><span>MONTH RETURN<strong>{percent(w.replay_return)}</strong></span><span>WITHIN-MONTH DRAWDOWN<strong>{percent(w.replay_drawdown)}</strong></span></div><Chart height={220} data={[{type:'scatter',mode:'lines',x:curve.map(e=>e.date),y:curve.map(e=>e.nav),line:{color:'#7564ce',width:2.5},name:'Continuous NAV'}]}/></>:<div className="empty"><Layers3 size={32}/><h3>Window results have not been computed</h3><p>This timeline describes the protocol. The selected experiment has no recorded rolling decisions for {w.month}. No performance is inferred from the diagram.</p></div>}</section><section className="panel"><div className="section-heading"><div><h2>{computed?'The selected rule':'What carries across the boundary?'}</h2><p>{computed?`Information cutoff: ${w.signal_date}`:'One portfolio through all twelve months.'}</p></div></div>{computed?<><span className="tag purple">{w.candidate_id===null?'CASH FALLBACK':`CANDIDATE ${w.candidate_id+1}`}</span><dl className="parameter-list">{Object.entries(w.selected_params).map(([key,value])=><div key={key}><dt>{labels[key]||key.replaceAll('_',' ')}</dt><dd>{key.includes('threshold')&&!key.includes('_ma')||key==='exposure'?percent(value):String(value)}</dd></div>)}</dl><p className="muted">Validation ranking combines Sharpe (50%), lower drawdown (30%) and lower turnover (20%). Ties prefer less parameter change.</p></>:<>{['Existing shares and cash','Unfinished entry tranches','Trading costs and settlement','The complete equity history'].map(s=><div className="check-line" key={s}><Check size={16}/>{s}</div>)}<p className="muted">The final Sharpe uses the full year of daily net returns, including cash days.</p></>}</section></div>
  {computed&&<section className="panel archive"><div className="section-heading"><div><h2>Why this candidate?</h2><p>Validation observations available before {w.month}. Monthly replay returns are not part of this selection score.</p></div></div><div className="table-scroll"><table><thead><tr><th>Candidate</th><th>Validation Sharpe</th><th>Drawdown</th><th>Turnover</th><th>Trades</th><th>Selection score</th><th>Outcome</th></tr></thead><tbody>{w.validation_candidates.map((r:Row)=><tr key={r.candidate_id}><td>#{r.candidate_id+1}</td><td>{numeric(r.sharpe)}</td><td>{percent(r.max_drawdown)}</td><td>{numeric(r.turnover)}×</td><td>{r.fills}</td><td>{numeric(r.selection_score)}</td><td><span className={w.candidate_id===r.candidate_id?'tag purple':'tag'}>{w.candidate_id===r.candidate_id?'SELECTED':r.selection_score===undefined?'INELIGIBLE':'ALTERNATIVE'}</span></td></tr>)}</tbody></table></div></section>}{computed&&<section className="panel archive"><h2>The full calibration field</h2><p className="muted">All candidates, including those outside the validation shortlist.</p><div className="table-scroll"><table><thead><tr><th>Candidate</th><th>Rule parameters</th><th>Calibration Sharpe</th><th>Drawdown</th><th>Trades</th></tr></thead><tbody>{(run.selection_trials||[]).filter(r=>r.month===w.month&&r.phase==='calibration').map(r=><tr key={r.candidate_id}><td>#{r.candidate_id+1}</td><td>{Object.entries(JSON.parse(r.params)).map(([k,v])=>`${labels[k]||k}: ${v}`).join(' · ')}</td><td>{numeric(r.sharpe)}</td><td>{percent(r.max_drawdown)}</td><td>{r.fills}</td></tr>)}</tbody></table></div></section>}</>;
}
