import {useState} from 'react';
import {ArrowUpRight,Search} from 'lucide-react';
import Chart from './Chart';
type Row=Record<string,any>;
const pct=(v:number)=>`${(v*100).toFixed(1)}%`;
export default function SearchEvidence({trials,select}:{trials:Row[];select:(id:string)=>void}) {
  const good=trials.filter(t=>t.state==='completed'&&t.metrics.sharpe!==null);
  const [picked,setPicked]=useState<Row>();
  if(!trials.length)return null;
  return <section className="panel archive"><div className="section-heading"><div><h2>The exploration behind the result</h2><p>{trials.length} recorded attempts · {good.length} candidates with a defined Sharpe · target-period optimization</p></div><span className="tag purple">ALL ATTEMPTS RETAINED</span></div><div className="search-grid"><Chart height={290} data={[{type:'scatter',mode:'markers',x:good.map(t=>Math.abs(t.metrics.max_drawdown)),y:good.map(t=>t.metrics.sharpe),customdata:good.map(t=>t.candidate_id),text:good.map(t=>`#${t.candidate_id+1} · ${t.params.strategy||'candidate'}`),hovertemplate:'%{text}<br>Drawdown %{x:.1%}<br>Sharpe %{y:.2f}<extra></extra>',marker:{size:good.map(t=>t.run_id?12:8),color:good.map(t=>t.run_id?'#7863c7':'#b6b0d8'),line:{color:'#fff',width:1}}}]} layout={{hovermode:'closest',xaxis:{title:{text:'Maximum drawdown'},tickformat:'.0%',gridcolor:'#f0edf5'},yaxis:{title:{text:'Sharpe ratio'},gridcolor:'#f0edf5'},margin:{l:55,r:20,t:15,b:45},shapes:[{type:'line',x0:.25,x1:.25,y0:0,y1:1,yref:'paper',line:{color:'#c7bda6',dash:'dot',width:1}},{type:'line',x0:0,x1:1,xref:'paper',y0:1.5,y1:1.5,line:{color:'#b9cfca',dash:'dot',width:1}}]}} onClick={event=>{const id=event.points[0]?.customdata;setPicked(good.find(t=>t.candidate_id===id));}}/><div className="candidate-card">{picked?<><span className="eyebrow">CANDIDATE {picked.candidate_id+1}</span><h3>{String(picked.params.strategy||'Strategy').replaceAll('_',' ')}</h3><div className="candidate-metrics"><span>Sharpe<strong>{picked.metrics.sharpe.toFixed(2)}</strong></span><span>Drawdown<strong>{pct(Math.abs(picked.metrics.max_drawdown))}</strong></span></div><dl className="parameter-list">{Object.entries(picked.params).filter(([k])=>k!=='strategy').map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v)}</dd></div>)}</dl>{picked.run_id?<button className="button" onClick={()=>select(picked.run_id)}>Open saved case<ArrowUpRight size={15}/></button>:<p className="muted">Metrics are retained for every candidate. Full trade-level results are stored for the three featured cases.</p>}</>:<><Search size={24}/><h3>Select a candidate</h3><p>Each point is an actual backtest. Explore the return-risk trade-off and inspect saved cases.</p><small>Dashed guides: Sharpe 1.5 and drawdown 25%.</small></>}</div></div></section>;
}
